name: enums
version: 0.2.1
author: Steven Roose <stevenroose@gmail.com>
description: A library to create Enums in Dart.
homepage: https://github.com/stevenroose/dart-enums
dependencies:
  collection: any
dev_dependencies:
  browser: any
  unittest: any